### ISSUE TITLE
[Compat] Knight_quest

### ISSUE THREAD

**Issue by GreenForzeGaming** [GizmoTheMoonPig/OpenBlocksTrophies#1]
### Mod Suggestion

https://www.curseforge.com/minecraft/mc-mods/knight-quest

### Why Should It Be in the Mod?

there is some really nice rare mobs in this mod and it also adds a really cool armory

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.
- [X] I have confirmed this mod does not make use of Geckolib. Geckolib models dont stay static when displaying as trophies, and because of this I have decided not to add them until I find a workaround or Geckolib fixes this problem.

**Comment by GreenForzeGaming** [comment]
no?

**Comment by GizmoTheMoonPig** [comment]
sorry this took so long! Ive been pretty busy with quite a few projects, but I finally got around to doing this. I'll have an update on curseforge out soon

**Comment by GreenForzeGaming** [comment]
YAY
