### ISSUE TITLE
[1.19.4 Forge] Crash when opening creative inventory

### ISSUE THREAD

**Issue by MrKashew** [GizmoTheMoonPig/OpenBlocksTrophies#11]
### Mod Version

2.2

### Client Log

https://gist.github.com/MrKashew/32ec944ceeb924332ce9588fef87a578

### Crash Report (if applicable)

https://gist.github.com/MrKashew/3b76a02ac6edd08f87dca5d039d5e3b6

### Bug Description

see logs

### Steps to Reproduce

opening creative inventory in sp, searched "flying"

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
update rats to 8.0.4
