### ISSUE TITLE
OpenBlocksTrophies 3.0.4 - Forge 1.20 is asking for a version of Twilight Forest I don't think exist?

### ISSUE THREAD

**Issue by CsillaAria** [GizmoTheMoonPig/OpenBlocksTrophies#12]
### Mod Version

OpenBlocksTrophies-1.20.1-3.0.4.jar

### Client Log

https://gist.github.com/CsillaAria/691904d45a8523938e672616d321023d

### Crash Report (if applicable)

https://gist.github.com/CsillaAria/3a400fc1836070a9761ee5df0845df9b

### Bug Description

The game has a loading error and I get the message: Mod obtroophies only supports twilightforest 4.3.1821 or above Currently, twilightforest is 4.3.1809

4.3.1809 is the highest version of Twilight Forest I can find. 

### Steps to Reproduce

The game crashes when loading, and is asking for a version of the Twilight Forest mod I don't think exists. 

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Crap, I forgot I added that so TF trophies don't crash. I'll see if I can get TF updated soon on curseforge, but for now here's a link to a dev build that should fix the issue: [build](https://artprodcus3.artifacts.visualstudio.com/Abaabfa6c-deea-4587-ba05-c308c2597b7a/1ef09d39-06cf-41fa-ad98-7258b70c2a72/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3RlYW10d2lsaWdodC9wcm9qZWN0SWQvMWVmMDlkMzktMDZjZi00MWZhLWFkOTgtNzI1OGI3MGMyYTcyL2J1aWxkSWQvMzM1NC9hcnRpZmFjdE5hbWUvUmVsZWFzZQ==0/content?format=file&subPath=%2Ftwilightforest-1.20.1-4.3.1844-universal.jar)

**Comment by CsillaAria** [comment]
That fixed the problem! Thank you.

**Comment by GizmoTheMoonPig** [comment]
New TF version has released now for anyone still having this issue. Make sure to update! https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest/files/4743133
