### ISSUE TITLE
[Suggestion] [mythic-mounts]

### ISSUE THREAD

**Issue by GreenForzeGaming** [GizmoTheMoonPig/OpenBlocksTrophies#15]
### The Suggestion [mythic-mounts]

https://www.curseforge.com/minecraft/mc-mods/mythic-mounts

### Why Should It Be in the Mod?

they finally made this mod a forge version and its amazing

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
unfortunately, I tried this and the entities were really glitchy as trophies. I can't fix it as the mod isn't open source, so im gonna have to unfortunately pass this one up. Sorry :(

**Comment by GreenForzeGaming** [comment]
no problems dude. love your extreme efforts! thx regardless!
