### ISSUE TITLE
[Suggestion] Alex Caves Support

### ISSUE THREAD

**Issue by GreenForzeGaming** [GizmoTheMoonPig/OpenBlocksTrophies#17]
### The Suggestion

the mod alex caves adds tons of new mobs. it just released but i love this mod and cant wait too see as many great mods have trophies. 

### Why Should It Be in the Mod?

alex caves adds allot of new cool mobs that i think deserve trophies

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
planned, just havent had time to do it yet as the mod just released today. It'll be out next update with a few other supported mods

**Comment by GreenForzeGaming** [comment]
aah no problem. also seems as thought there is a bug causing the trophie mod and alexes caves not working together

**Comment by GizmoTheMoonPig** [comment]
yeah its because of an incompatibility with Twilight Forest, should hopefully be fixed in the next release of AC. It was fixed already on github
