### ISSUE TITLE
crash with alex caves

### ISSUE THREAD

**Issue by GreenForzeGaming** [GizmoTheMoonPig/OpenBlocksTrophies#18]
### Mod Version

3.0.4

### Crash Report (if applicable)

https://gist.github.com/GreenForzeGaming/63f02551f0e23ff012053e6a77460e1a

### Bug Description

game crashes when trying to render trophies in JEI

### Steps to Reproduce

start game scroll through jei and it crashes. idk if more mods are at cause but both mods cant be on at the same time for me.

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
issue with Alex's Caves and Twilight Forest's Naga. Will be fixed next AC release, this isnt on me

**Comment by GreenForzeGaming** [comment]
but i can run twilight forest and AC

wierd

**Comment by GizmoTheMoonPig** [comment]
try summoning a naga, itll crash

**Comment by GizmoTheMoonPig** [comment]
fix was uploaded: https://legacy.curseforge.com/minecraft/mc-mods/alexs-caves/files/4806629
