### ISSUE TITLE
[Compat] trophies for ice and fire and the newly made Alex's caves

### ISSUE THREAD

**Issue by pantsguyapp** [GizmoTheMoonPig/OpenBlocksTrophies#19]
### Mod Suggestion

I want the trophies of mobs from those mod

### Why Should It Be in the Mod?

Trophies from all the mobs from the mods, all variants of the dragons if possible and the dragons should have a decent size in the trophies, not just tiny.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.
- [X] I have confirmed this mod does not make use of Geckolib. Geckolib models dont stay static when displaying as trophies, and because of this I have decided not to add them until I find a workaround or Geckolib fixes this problem.

**Comment by GizmoTheMoonPig** [comment]
3.1 includes trophies for both of these mods. The dragons are small so they actually fit on the pedestal and this won't be changing so they fit with all the other trophies the mod adds
