### ISSUE TITLE
[1.19.3] Client crash when on a dedicated server scrolling through creative menu.

### ISSUE THREAD

**Issue by ProsperCraft** [GizmoTheMoonPig/OpenBlocksTrophies#2]
### Mod Version

3-1.6

### Crash Report (if applicable)

https://gist.github.com/ProsperCraft/80839ac5208e4b929493a95eb1d6f702

### Bug Description

Scrolling through the creative menu it can't render something and crashes the client.

### Steps to Reproduce

open creative menu on TownCraft for 1.19.3
go to trophies page 
crash

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
ugh, of course thats broken on servers. I'll have a fix in a bit

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/bac85bb28a0f44f14d0096a20fc74052  happened again.

**Comment by GizmoTheMoonPig** [comment]
found the issue. Apparently if the game tries to load a render of the camel trophy when it its feature flag isnt enabled on the server everything crashes and burns. Im just gonna remove it until 1.20 drops, no point in me messing with feature flag logic

**Comment by GizmoTheMoonPig** [comment]
fixed in 3420d9e77d243849fa43d93f791b3e77d589919b, will have a build uploaded to CF soon
