### ISSUE TITLE
[Compat] Ice and Fire trophy suggestions

### ISSUE THREAD

**Issue by pantsguyapp** [GizmoTheMoonPig/OpenBlocksTrophies#20]
### Mod Suggestion

Ice and Fire

### Why Should It Be in the Mod?

The Ender Dragon trophy has a bigger model than the dragons from the mods, upscale it so that all dragons can have equal size.
Ice and Fire dragons should use adult cries instead of juvenile cries when right clicked, and the cries should be louder too.
Baby cockatrices should also have a trophy too, since they have a different baby models.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.
- [X] I have confirmed this mod does not make use of Geckolib. Geckolib models dont stay static when displaying as trophies, and because of this I have decided not to add them until I find a workaround or Geckolib fixes this problem.

**Comment by GizmoTheMoonPig** [comment]
I can make the trophies bigger (even though I like their current size, but whatever), but I can't change the volume nor the sound that plays. The sound itself is controlled through the dragon's age which is always the default serverside (NBT changes done via trophy jsons are only done on the client for rendering purposes)
Baby cockatrices won't be getting trophies as baby mobs don't drop loot.

**Comment by pantsguyapp** [comment]
What about the 3 easter egg gryphs are there trophies available for the 2 special ones that need to be summoned?

**Comment by GizmoTheMoonPig** [comment]
I think so? I added all the variants I saw in the enum here: https://github.com/AlexModGuy/Ice_and_Fire/blob/1.20/src/main/java/com/github/alexthe666/iceandfire/enums/EnumHippogryphTypes.java#L14-L23. 
If there are any name easter egg ones you can get them by renaming the trophy
