### ISSUE TITLE
Crashes with Occultism

### ISSUE THREAD

**Issue by Xiaolin2-g** [GizmoTheMoonPig/OpenBlocksTrophies#23]
### Mod Version

OpenBlocksTrophies-1.20.1-3.1.10

### Crash Report (if applicable)

https://mclo.gs/np5H5mp

### Bug Description

This item: `obtrophies:trophy{BlockEntityTag:{VariantID:0,entity:"occultism:afrit"}}` crashes the game.

Tested on a clean instance of Minecraft, it's not another unrelated mod.

### Steps to Reproduce

1. Have this mod and Occultism installed.
2. Search "trophies" in the creative inventory or JEI.
3. The moment you type the "p", the game crashes.

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
sorry im 2 weeks late! 
This is an issue with the version of SmartBrainLib youre using. Use this version instead: https://www.curseforge.com/minecraft/mc-mods/smartbrainlib/files/4743400. Forge broke something regarding brains after the neoforge split so there's a few different versions of SmartBrainLib. The one I linked will fix your issue.
