### ISSUE TITLE
secondary effect issue

### ISSUE THREAD

**Issue by GreenForzeGaming** [GizmoTheMoonPig/OpenBlocksTrophies#27]
### Mod Version

4.0.0

### Bug Description

trophies secondary effect cant be turned off in config
and if there is no secondary effects.
right clicking a squid trophy spawns a waterblock above it

### Steps to Reproduce

place trophie
right click

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
the water block thing is intended, as that what OpenBlocks did with their trophy, but I see how this could be an issue. I'll add a config option to turn off right click effects soon

**Comment by GizmoTheMoonPig** [comment]
added in 7184fc63d0c6cb400b8b4c03c804387e38b838b4. I'll backport it to 1.20.1 later if I feel like it, but for now itll just be on 1.20.4

**Comment by GreenForzeGaming** [comment]
was looking into this it seems you havnt gotten it into 1.20.1 yet. i hope you get some time some day. again thx for a great mod and experience with issues and addons!

**Comment by GreenForzeGaming** [comment]
i guess this is still not added yet. i was really hoping to be able to have the trophies not do wierd stuff as people tend too troll.
still playing in 1.20.1

**Comment by GreenForzeGaming** [comment]
@GizmoTheMoonPig i need this so bad lol
