### ISSUE TITLE
[Compat] irons-spells-n-spellbooks

### ISSUE THREAD

**Issue by GreenForzeGaming** [GizmoTheMoonPig/OpenBlocksTrophies#28]
### Mod Suggestion

https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks

### Why Should It Be in the Mod?

i think its a cool mod and the mages would be cool to get as trophies.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.
- [X] I have confirmed this mod does not make use of Geckolib. Geckolib models dont stay static when displaying as trophies, and because of this I have decided not to add them until I find a workaround or Geckolib fixes this problem.

**Comment by GizmoTheMoonPig** [comment]
Added in the latest version uploaded to Curseforge (4.1.9) :)

**Comment by GreenForzeGaming** [comment]
> Added in the latest version uploaded to Curseforge (4.1.9) :)

freaking legend!. lol feels like half the trophies been suggested by me XD, thx for your work dude. very appriciated
