### ISSUE TITLE
dissapear

### ISSUE THREAD

**Issue by GreenForzeGaming** [GizmoTheMoonPig/OpenBlocksTrophies#4]
### Mod Version

2.0.0

### Bug Description

throphy vanishes if broken with anything else but pickaxe

### Steps to Reproduce

place

break with hand

trophy gone

sad player

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
trophies are meant to be broken with a pickaxe, but i'll make it so it doesnt require one to break them

**Comment by GreenForzeGaming** [comment]
wounderfull!
