### ISSUE TITLE
added in an older version but has now been reforged

### ISSUE THREAD

**Issue by GreenForzeGaming** [GizmoTheMoonPig/OpenBlocksTrophies#41]
### The Suggestion

Knight Quest [reforged] 
https://www.curseforge.com/minecraft/mc-mods/knight-quest-reforged

### Why Should It Be in the Mod?

it has been added before

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
Added in 5.0, but only in 1.21. I completely forgot to pull that over to 1.20 as I was updating branches. Ive decided though that Im not gonna be messing with 1.20 anymore as I dont have time to maintain multiple versions. Youre more than welcome to take the configs from the 1.21 version and make a datapack to add them in
