### ISSUE TITLE
the breaking particles of the magma cube tropy causes hard client crash

### ISSUE THREAD

**Issue by scopiplays** [GizmoTheMoonPig/OpenBlocksTrophies#43]
### Mod Version

OpenBlocksTrophies-1.21-4.3.27

### Client Log

https://gist.github.com/scopiplays/01bab1487e0d85d19b2a04205b8f74a3

### Crash Report (if applicable)

https://gist.github.com/scopiplays/e9341f63e68c2fbe600776725e8e2af3

### Bug Description

attempting to break the open blocks magma cube trophy causes hard client crash

### Steps to Reproduce

1. place trophy
2. punch it
3. boom

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
Issue with Neat, update to 1.21-39 or higher to fix it
