### ISSUE TITLE
[Suggestion] Add support for the new  Maledictus boss from l'enders cataclysm as well marium soulslike weaponry and legendary monsters

### ISSUE THREAD

**Issue by DeadGator** [GizmoTheMoonPig/OpenBlocksTrophies#44]
### The Suggestion

And maybe modify the base for trophies instead of a black stand, maybe  a golden one or a pillar made from quartz?

![image](https://github.com/user-attachments/assets/94d2c239-1755-4ed7-8704-aba6538931c3)

### Why Should It Be in the Mod?

More compatibility

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
Next time please split things like this into multiple tickets. 
All mods suggested in the title have been updated/added in the newest build (5.0) which will be up shortly. 
I will not be changing the trophy pedestal in the base mod, however you can easily do it yourself with a resource pack
