### ISSUE TITLE
Left click squid statue CTD

### ISSUE THREAD

**Issue by Cinder85** [GizmoTheMoonPig/OpenBlocksTrophies#45]
### Mod Version

1.21-4.3.27

### Crash Report (if applicable)

https://gist.github.com/Cinder85/7c21183ebd4cae879ec7fad23fa718e3

### Bug Description

Left clicking any statue, but tested with squid statue Causes a CTD from the game

### Steps to Reproduce

Place statue, Left click statue, Boom Crash

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this seems to be the same crash as #43, can you try removing sodium? I have a feeling theyre messing with something

**Comment by Cinder85** [comment]
We already tried removing sodium and it did the same thing

**Comment by GizmoTheMoonPig** [comment]
Finally tracked it down. Its an issue with Neat, update to 1.21-39 or higher to fix it
