### ISSUE TITLE
[Suggestion] Drop Setting

### ISSUE THREAD

**Issue by MokahTGS** [GizmoTheMoonPig/OpenBlocksTrophies#47]
### The Suggestion

If I set the override in the config to 0.0 does that turn off trophies dropping completely?  If not can we have that option?

### Why Should It Be in the Mod?

This would help modpacks that want to use trophies as quest rewards.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
Yes, it does that already
