### ISSUE TITLE
micheal jackson leen

### ISSUE THREAD

**Issue by GreenForzeGaming** [GizmoTheMoonPig/OpenBlocksTrophies#5]
### Mod Version

2.0.0

### Bug Description

statues keep aiming at players makes them look wierd

### Steps to Reproduce

![2023-04-01_11 00 44](https://user-images.githubusercontent.com/62345403/229276665-54a37636-6ae6-4f1e-ba47-2173b3411ee0.png)

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
April fools! It'll go back to normal tomorrow

**Comment by GreenForzeGaming** [comment]
damn,thats a good one XD. hats off for that one! if anything, delete this post so it can stay hidden for as long as possible XP
