### ISSUE TITLE
[Compat] 

### ISSUE THREAD

**Issue by GreenForzeGaming** [GizmoTheMoonPig/OpenBlocksTrophies#7]
### Mod Suggestion

https://www.curseforge.com/minecraft/mc-mods/unusual-prehistory-forge

### Why Should It Be in the Mod?

i love this mod and i do know it uses geckolib, but i dont know if all of them do or if theres been a fix for the non static trophies yet

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.
- [X] I have confirmed this mod does not make use of Geckolib. Geckolib models dont stay static when displaying as trophies, and because of this I have decided not to add them until I find a workaround or Geckolib fixes this problem.

**Comment by GizmoTheMoonPig** [comment]
i'll check out if this mod works with trophies if/when it updates, will keep it open until then. I unfortunately don't have enough free time nor motivation to continue supporting 1.19.2

**Comment by GizmoTheMoonPig** [comment]
noticed this mod finally updated for 1.20.1 and quickly learned it has the geckolib curse after trying to add the trophies, so I unfortunately cant support it
