### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by GreenForzeGaming** [GizmoTheMoonPig/OpenBlocksTrophies#8]
### The Suggestion

revamped base texture for the trophies
![Zombie](https://user-images.githubusercontent.com/62345403/230303064-3dc5038d-742b-4f8e-afb6-ad917808f075.png)
this is just the anvil texture from minecraft itself, it shares the same texture size and i think it looks good!

### Why Should It Be in the Mod?

i think the old texture could use a little touchup

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
I've decided after thinking about it for some time that I don't want to change the original texture. I like how it looks, but if you don't you're more than welcome to change it yourself with a resource pack. Sorry if that's not the answer you wanted for this
