### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Minebrah** [GizmoTheMoonPig/OpenBlocksTrophies#9]
### Mod Version

1.19-2.1

### Crash Report (if applicable)

https://gist.github.com/Minebrah/e4e30e2749dd57dd4a124dfaa880996b

### Bug Description

I think it crashed when trying to render a trophy?

### Steps to Reproduce

I threw some tnt at a bunch of mobs that were chasing me and my game crashed. I'm unable to join the world with the mod installed making it softlocked.

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
sorry this took so long! Ive been limited on free time lately and I figured since I was tackling the port to 1.20 I would solve this too. Because of my limited time this fix will only apply to 1.20, sorry
